---
abstract: 'collection of functions for checking credit card numbers'
author:
  - 'Michael Robinton <michael@bizsystems.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.3
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CCCheck
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Business-CCCheck
  repository: https://github.com/neilbowers/Business-CCCheck
version: 0.07
